build:
     command: npm run build
     commandOrigin: config
     environment:
       - NODE_VERSION
       - YARN_VERSION
     publish: /opt/build/repo/dist
     publishOrigin: config
     redirects:
     - from: /*
      status: 200
      to: /index.html
  redirectsOrigin: config
